name: 🚀 Deploy website on push to master
on:
  push:
    branches: [ master ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --optimize-autoloader --no-dev
      - name: Generate key
        run: php artisan key:generate
      - name: Database Migration
        run: php artisan migrate
      - name: Optimize clear
        run: php artisan optimize:clear
      #      - name: Directory Permissions
      #        run: chmod -R 777 storage bootstrap/cache

      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "*"
          target: "portfolio.abdullahalmamun.xyz"
